version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  labels: [ ]
  schedule:
    interval: weekly
  open-pull-requests-limit: 20
  ignore:
    - dependency-name: "@types/node"
    - dependency-name: "@types/vscode"
  groups:
    eslint:
      patterns:
        - "esbuild"
        - "eslint*"
        - "@typescript-eslint/*"
    microsoft-vscode:
      patterns:
        - "@microsoft/vscode*"
- package-ecosystem: github-actions
  directory: "/"
  labels: [ ]
  schedule:
    interval: weekly
