version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  labels: [ ]
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  groups:
    eslint:
      patterns:
        - "esbuild"
        - "eslint*"
        - "@typescript-eslint/*"
    types:
      patterns:
        - "@types/*"
    microsoft-vscode:
      patterns:
        - "@microsoft/vscode*"
- package-ecosystem: github-actions
  directory: "/"
  labels: [ ]
  schedule:
    interval: weekly
